### PR TITLE
Cleanup gh actions

### PR DESCRIPTION
**Pull request by fisx**
There was a dhall script that generates the gh workflow, but it was only documented in the commit message.  I poured the commit message into a shell script, did some renaming, and realized that the yaml file was (slightly) outdated.  If we don't want to change the yaml file, I think it's also an improvement to only merge the first commit and leave the yaml file out of sync for now.

### CODE REVIEW

**Comment by fisx** [comment]
Come to to think of it, and after I just tried to bump the ghc versions and found that they are not supported by `github-actions-dhall`: what about deprecating `ci.dhall` and `ci.sh`, leaving it here for documentation and future work, and updating the yaml file from now on?

**Comment by sorki** [comment]
Thank you!

Out of sync is caused by couple of pending PRs:

https://github.com/vmchale/github-actions-dhall/pull/3
https://github.com/vmchale/github-actions-dhall/pull/4
https://github.com/vmchale/github-actions-dhall/pull/6

I've added all of them to [pending branch of my fork](https://github.com/vmchale/github-actions-dhall/compare/master...sorki:pending)  so you can try switching to it:

```dhall
haskellCi = https://raw.githubusercontent.com/sorki/github-actions-dhall/pending/haskell-ci.dhall
```

**Comment by sorki** [comment]
Needs a bit more maintenance but I've got no response yet - I can bump GHC versions as well. This is an experiment but I would prefer not to edit `yaml` files by hand if they can be generated (and also re-used between projects).

**Comment by fisx** [comment]
> Needs a bit more maintenance but I've got no response yet - I can bump GHC versions as well. This is an experiment but I would prefer not to edit `yaml` files by hand if they can be generated (and also re-used between projects).

Makes perfect sense, thanks for the link!  I don't think we need to rush bumping ghc versions, as long as the old (minor) versions are working fine.

**Comment by sorki** [comment]
I've updated the branch to include recent GHCs and switched the haskell setup action to https://github.com/haskell/actions since the original is deprecated, see https://github.com/vmchale/github-actions-dhall/compare/master...sorki:pending

Also it looks like we can do GHC8104 and GHC901 as well https://github.com/sorki/haskell-project-template/pull/1

**Comment by fisx** [comment]
Like this?  Thanks!  :)

**Comment by sorki** [comment]
Nice! Now we just need fixes for GHC 9 :D

**Comment by fisx** [comment]
D'OH!  :)

**Comment by sorki** [comment]
I think you can drop GHC9 for now, I've tried it,  sort-of fixed one issue with `data-lens-light` https://github.com/UnkindPartition/data-lens-light/pull/10 and got stuck [on weird one with profunctors](https://github.com/ekmett/profunctors/issues/96). I except few more to pop-up so it seem safe to say ecosystem is not quite there yet.

**Comment by fisx** [comment]
thanks @sorki !  @julialongtin ready to merge?

**Pull request merged**
