### PR TITLE
Make rotateExtrude operate in radians

### LINKED ISSUE #288: RotateExtrude should use radians not degrees
Most of ImplicitCAD uses Radians, but the `RotateExtrude` implementation uses degrees:
https://github.com/colah/ImplicitCAD/blob/5ddd75006cc8f1d6a0e184f56c3714a9097ce6b0/Graphics/Implicit/ObjectUtil/GetImplicit3.hs#L170-L176

This is a breaking change, but I think we should change the API to use radians not degrees. Fwiw, I use `RotateExtrude` to implement a screw, and I calculate a number of rotations anyways and then have to convert to degrees for this function.

This was prompted by https://github.com/colah/ImplicitCAD/pull/287#issuecomment-727626798. Note that I'm mostly thinking about the Haskell eDSL side, I have no familiarity with ExtOpenScad.

### PR DESCRIPTION
**Pull request by isovector**
Before, rotateExtrude operated over degrees for compatability reasons
with scad. This is an odd choice for the haskell library itself, so
instead we make rotateExtrude do the right thing, and put a shim into
openscad to make the transformation.

Fixes #288

### CODE REVIEW

**Review by julialongtin — APPROVED** [review]

**Comment by julialongtin** [comment]
Can we get a test for this?

**Comment by isovector** [comment]
I'm not sure what a test would look like for this. Any suggestions?

**Comment by julialongtin** [comment]
Sure. Use the fact that a complete rotation is identical to a un-rotated
object as the test, both in scad, and in haskell.

**Comment by isovector** [comment]
As far as I can tell, `rotateExtrude` is hopelessly broken (#307, #308, #309, #310), so I'm not sure these tests will be conclusive.

**Pull request merged**
