### PR TITLE
[wip] Remove partial functions

### LINKED ISSUE #304: unionR r [] crashes
```haskell
unionR r []
```

corrupts a mesh so that it contains no triangles. Instead, it should produce a zero volume solid.

### PR DESCRIPTION
**Pull request by isovector**
This PR is looking good, but I want to implement #318 to get confidence in it.

Fixes #304 and #306.

### CODE REVIEW

**Comment by julialongtin** [comment]
So do you think this is no longer a draft? if so, please click 'ready for review'.

**Comment by isovector** [comment]
I think I'm waiting for #324 to land before I move forwards on this. I'd like to have a lot of tests in place to make sure I don't break anything here, because it's quite an invasive change.

**Comment by julialongtin** [comment]
324 is now merged. now, should we look at merging this? ;)

**Comment by isovector** [comment]
Subsumed by #331

**Pull request closed without merging**
