### PR TITLE
Add support for mirroring

### PR DESCRIPTION
**Pull request by isovector**
This PR adds a `mirror` method to `Object` which mirrors an object across a hyperplane defined by a given normal.

Example:

```haskell
let cutcube =
      difference
        [ rect3R 0 (-3, 0, -3) (0, 3, 0)
        , sphere 3
        ]
 in union
      [ cutcube
      , mirror (1, 0, 1) cutcube
      ]
```

2020-11-23-090402_357x295_scrot

### CODE REVIEW

**Comment by julialongtin** [comment]
yeah, you're going to have to fix rotation, AND expose this via scad for me to accept it.

**Comment by isovector** [comment]
@julialongtin PTAL. The arbitrary reflection axis is now implemented, though I'm going to push back against the scad stuff. I don't use that interface, nor do I have any plan to. If someone else would like to expose this functionality, I'd be all for it, but this PR provides useful functionality as it is.

**Comment by isovector** [comment]
Whoops, I found a bug in the bounding box computation. When the mirror axis isn't colinear with the world axis, it can cull some of the corners. I think the solution here is to reflect every corner of the bounding box, rather than just the two opposite ones.

**Comment by julialongtin** [comment]
After discussion with the OpenSCAD folks, this is more powerful than their mirror() construct. I have two asks with this one: could you rename this version reflect(), and could you implement a mirror() that does not include the original object in the output? no and no is a fine answer, don't hurt me for asking. :)

**Comment by isovector** [comment]
This version doesn't include the original object either --- notice the `union` in the example!

**Review by julialongtin — APPROVED** [review]

**Pull request merged**
