### PR TITLE
Add golden test machinery

### PR DESCRIPTION
**Pull request by isovector**
This PR adds a new GoldenTestSpec, which exposes a `golden` combinator for building golden tests. These tests take a SymbolicObj3, and will raytrace it, checking the resulting STL against a known-good version. The result is a robust system for ensuring mesh generation doesn't subtly change when working on the underlying infrastructure.

@julialongtin, you seemed somewhat against golden tests in our brief discussion on IRC. I'd urge you to reconsider;  checking in the test result artifacts has the benefit that changes which (intentionally or otherwise) modify the mesh generation must come with a corresponding diff to the tests. This gives at-a-glance review-time reassurance that no bugs have been smuggled in. 

Furthermore, it reifies your testing strategy of "check out the old branch, build some STLs, hash them, check out the new branch, build the same STLs, and compare the hashes" --- allowing other contributors to share that testing burden with you (albeit in an automated way.) The current makefile-based solution doesn't work at all for stack-managed GHC installs, and as we've seen on the GHC codebase, this is a surprisingly difficult problem to get right. Simpler for everyone to just put it into Haskell.

### CODE REVIEW

**Review by julialongtin — APPROVED** [review]
Code speaks loudly. This looks great. Gladly approved!

**Comment by isovector** [comment]
Excellent! In that case I'll do some more work on it tomorrow to get everything nicely polished here.

**Comment by isovector** [comment]
@julialongtin PTAL

**Comment by isovector** [comment]
I plan to follow up this PR with another that copies the haskell examples in as golden tests.

**Review by julialongtin — APPROVED** [review]

**Pull request merged**
